# Gradle 属性
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Minecraft / Fabric 版本（与 Forge 原版同为 1.20.1）
minecraft_version=1.20.1
loader_version=0.16.14
fabric_version=0.92.12+1.20.1

# 模组属性（与 Forge 原版保持一致）
mod_version=1.1.0-fabric
mod_group_id=com.pla.smart_npc
mod_authors=pla_is_me
mod_description=Adds Smart NPCs to make your world more enjoyable.
